// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-categories.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.49.9";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function requireAuth(ctx) {
  return ctx.isAuthenticated() ? null : {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data) }],
    structuredContent: { data }
  };
}

// src/lib/mcp/tools/list-categories.ts
var list_categories_default = defineTool({
  name: "list_categories",
  title: "List categories",
  description: "List the signed-in user's tracking categories, including colors, goal types and daily/weekly time goals.",
  inputSchema: {
    include_inactive: z.boolean().optional().describe("Include archived/inactive categories. Defaults to false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_inactive }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    let query = supabaseForUser(ctx).from("categories").select(
      "id, name, color, description, parent_id, level, goal_type, is_boolean_goal, boolean_goal_label, daily_time_goal_minutes, weekly_time_goal_minutes, is_active, sort_order"
    ).order("sort_order", { ascending: true });
    if (!include_inactive) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/list-activities.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_activities_default = defineTool2({
  name: "list_activities",
  title: "List logged activities",
  description: "List the signed-in user's logged time activities within an optional date range, newest first.",
  inputSchema: {
    from: z2.string().optional().describe("ISO date/time lower bound, e.g. 2026-07-01."),
    to: z2.string().optional().describe("ISO date/time upper bound, e.g. 2026-07-31."),
    category_id: z2.string().optional().describe("Only return activities in this category."),
    limit: z2.number().optional().describe("Maximum rows to return (1-200, default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, category_id, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const rows = Math.min(Math.max(limit ?? 50, 1), 200);
    let query = supabaseForUser(ctx).from("activities").select(
      "id, category_id, start_time, end_time, duration_minutes, notes, categories(name, color)"
    ).order("start_time", { ascending: false }).limit(rows);
    if (from) query = query.gte("start_time", from);
    if (to) query = query.lte("start_time", to);
    if (category_id) query = query.eq("category_id", category_id);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult(data ?? []);
  }
});

// src/lib/mcp/tools/log-activity.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var log_activity_default = defineTool3({
  name: "log_activity",
  title: "Log a time activity",
  description: "Log time spent on a category for the signed-in user. Duration is rounded to the nearest 15-minute increment.",
  inputSchema: {
    category_id: z3.string().describe("Category id from list_categories."),
    start_time: z3.string().describe("ISO start date/time of the activity."),
    duration_minutes: z3.number().describe("Duration in minutes (1-1440). Rounded to 15-minute increments."),
    notes: z3.string().optional().describe("Optional notes about the activity.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ category_id, start_time, duration_minutes, notes }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const start = new Date(start_time);
    if (Number.isNaN(start.getTime())) return errorResult("start_time is not a valid date/time.");
    const rounded = Math.min(Math.max(Math.round(duration_minutes / 15) * 15, 15), 1440);
    const end = new Date(start.getTime() + rounded * 6e4);
    const { data, error } = await supabaseForUser(ctx).from("activities").insert({
      user_id: ctx.getUserId(),
      category_id,
      start_time: start.toISOString(),
      end_time: end.toISOString(),
      date_time: start.toISOString(),
      duration_minutes: rounded,
      notes: notes?.slice(0, 1e3) ?? null
    }).select().single();
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-habits.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_habits_default = defineTool4({
  name: "list_habits",
  title: "List habits and recent logs",
  description: "List the signed-in user's habits with their targets, plus habit logs from the last N days.",
  inputSchema: {
    days: z4.number().optional().describe("How many days of logs to include (default 7, max 90).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    const window = Math.min(Math.max(days ?? 7, 1), 90);
    const since = new Date(Date.now() - window * 864e5).toISOString().slice(0, 10);
    const [habits, logs] = await Promise.all([
      supabase.from("habits").select("id, name, description, target_value, target_unit, is_active").eq("is_active", true),
      supabase.from("habit_logs").select("id, habit_id, log_date, value, notes").gte("log_date", since).order("log_date", { ascending: false })
    ]);
    if (habits.error) return errorResult(habits.error.message);
    if (logs.error) return errorResult(logs.error.message);
    return jsonResult({ habits: habits.data ?? [], logs: logs.data ?? [] });
  }
});

// src/lib/mcp/tools/log-habit.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^3.25.76";
var log_habit_default = defineTool5({
  name: "log_habit",
  title: "Log a habit value",
  description: "Record a habit value for a given day for the signed-in user. A habit counts as complete when the value reaches its target.",
  inputSchema: {
    habit_id: z5.string().describe("Habit id from list_habits."),
    value: z5.number().describe("Recorded value for the day, e.g. glasses of water."),
    log_date: z5.string().optional().describe("Date in YYYY-MM-DD. Defaults to today."),
    notes: z5.string().optional().describe("Optional notes for this log.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ habit_id, value, log_date, notes }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const date = log_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabaseForUser(ctx).from("habit_logs").insert({
      user_id: ctx.getUserId(),
      habit_id,
      log_date: date,
      value,
      notes: notes?.slice(0, 1e3) ?? null
    }).select().single();
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/index.ts
var projectRef = "flgbjadjravxlwjpblrr";
var mcp_default = defineMcp({
  name: "rollen-mcp",
  title: "Rollen",
  version: "0.1.0",
  instructions: "Tools for Rollen, a personal wellness and time tracking app. Use `list_categories` to discover the user's categories, `log_activity` to record time spent, `list_activities` to review logged time, and `list_habits`/`log_habit` for daily habit tracking. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_categories_default, list_activities_default, log_activity_default, list_habits_default, log_habit_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
