// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dhtgoqoapwxioayzbdfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRodGdvcW9hcHd4aW9heXpiZGZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTU5NjIsImV4cCI6MjA2NDQ3MTk2Mn0.2BVotbwna2jS1anRXs01UvBpAxXBwVlgMQbfwudXJYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);