// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flgbjadjravxlwjpblrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsZ2JqYWRqcmF2eGx3anBibHJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMTQxMzcsImV4cCI6MjA3NDg5MDEzN30.O6e_1Q13LZtMAb-LOKtnyNGoueMdXcjl1VJwc180ZCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);